version: '3'
services:
  webserver:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./wp-content:/var/www/html/wp-content

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wpdb

  client:
    image: debian:latest
    command: tail -f /dev/null
  
  waf:
    image: owasp/modsecurity-crs:apache
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"
